bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

galleriet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler403, handler404, handler405, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = 'galleriet.views.handler403'
handler404 = 'galleriet.views.handler404'
handler405 = 'galleriet.views.handler405'
handler500 = 'galleriet.views.handler500'

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete/<int:product_id>/', views.delete_product,
         name='delete_product'),
]

products/models.py
from django.db import models


MEDIUM = (
    (0, 'Oil'),
    (1, 'Acrylic'),
    (2, 'Watercolour'),
    (3, 'Pencil')
)


class Artist(models.Model):
    """
    Database model for Artist
    """
    full_name = models.CharField(max_length=254, unique=True)
    nationality = models.CharField(max_length=254, null=True, blank=True)
    email = models.EmailField(max_length=254, null=True, blank=True)
    phone_number = models.CharField(max_length=254, null=True, blank=True)
    added_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    """
    Database model for Category
    """

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    """
    Database model for Product
    """
    artist = models.ForeignKey('Artist', null=True, blank=True,
                               on_delete=models.SET_NULL)
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.TextField()
    medium = models.IntegerField(choices=MEDIUM, default=0)
    height = models.IntegerField()
    width = models.IntegerField()
    added_on = models.DateTimeField(auto_now_add=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False,
                             widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-grey'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.db.models.functions import Lower

from .models import Product, Category, Artist
from .forms import ProductForm


def all_products(request):
    """ A view to show all products, including sorting and search queries """

    products = Product.objects.all().order_by('-added_on')
    query = None
    categories = None
    artists = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 'artist' in request.GET:
            artists = request.GET['artist'].split(',')
            products = products.filter(artist__full_name__in=artists)
            artists = Artist.objects.filter(full_name__in=artists)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn't enter any search criteria")
                return redirect(reverse('products'))

            queries = (
                Q(name__icontains=query) | Q(description__icontains=query)
                )
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'
    paginator = Paginator(products, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_artists': artists,
        'current_sorting': current_sorting,
        'page_obj': page_obj,
    }

    return render(request, 'products/products.html', context)


def product_detail(request, product_id):
    """ A view to show individual product details """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to update product. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container my-5 pb-5 rounded bg-white">
    <div class="row">
        <div class="col-12 col-md-6">
            <br>
            <h2 class="logo-font mb-4">Product Management</h2>
            <p class="h5 text-muted">Add a Product</p>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="btn btn-grey" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-red" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container my-5 pb-5 rounded bg-white">
    <div class="row">
        <div class="col-12 col-md-6">
            <br>
            <h2 class="logo-font mb-4">Product Management</h2>
            <p class="h5 text-muted">Edit a Product</p>
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-6">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2"
                enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a class="btn btn-grey" href="{% url 'products' %}">Cancel</a>
                    <button class="btn btn-red" type="submit">Update Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_title %}Products -{% endblock %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
            <div class="image-container my-5">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank">
                    <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                </a>
                {% else %}
                <a href="#">
                    <img class="card-img-top img-fluid" src="{{ MEDIA_URL }}noimage.png" alt="{{ product.name }}">
                </a>
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4">
            <div class="product-details-container mb-5 mt-md-5 bg-white p-3 rounded">
                <p class="mb-0">{{ product.name }}</p>
                <p class="lead mb-0 text-left font-weight-bold">€{{ product.price }}</p>
                {% if product.category %}
                <p class="small mt-1 mb-0">
                    <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                        <i class="fas fa-tag mr-1"></i>{{ product.category.friendly_name }}
                    </a>
                </p>
                {% endif %}
                {% if product.artist %}
                <p class="small mt-1 mb-0">
                    <a class="text-muted" href="{% url 'products' %}?artist={{ product.artist }}">
                        <i class="fas fa-user mr-1"></i>{{ product.artist }}
                    </a>
                </p>
                {% endif %}
                <p class="mt-3">{{ product.description }}</p>
                <p>Medium: {{ product.get_medium_display | safe }}</p>
                <p>Height: {{ product.height }}cm</p>
                <p>Width: {{ product.width }}cm</p>
                {% if request.user.is_superuser %}
                <p>
                    <a href="{% url 'edit_product' product.id %}" class="btn btn-grey btn-sm"><i class="fa fa-edit"></i>
                        Edit</a>
                    <!-- Button trigger Product Delete modal -->
                    <button type="button" class="btn btn-red btn-sm" data-toggle="modal" data-target="#productModal"><i
                            class="fa fa-trash"></i> Delete</button>
                </p>
                <!-- Product Delete Modal -->
                <div class="modal fade" id="productModal" tabindex="-1" aria-labelledby="productModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="productModalLabel">Delete product</h5>
                                <button type="button" class="btn" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true"><i class="fas fa-xmark"></i></span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div style="padding: 10px;">
                                    <p class="font-weight-bold">
                                        {{ product.name }}
                                        &#8739;
                                        <span class="text-muted">
                                            €{{ product.price }}
                                        </span>
                                    </p>
                                    {% if product.image %}
                                    <img class="card-img-top img-fluid shadow" src="{{ product.image.url }}"
                                        alt="{{ product.name }}">
                                    {% else %}
                                    <img class="card-img-top img-fluid shadow" src="{{ MEDIA_URL }}noimage.png"
                                        alt="{{ product.name }}">
                                    {% endif %}
                                </div>
                                <p class="text-danger text-center">Are you sure you want to delete this product?</p>
                            </div>
                            <div class="modal-footer">
                                <form action="{% url 'delete_product' product.id %}" method="POST" class="d-inline">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-red">Delete</button>
                                </form>
                                <button type="button" class="btn btn-grey" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
                <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-12">
                            <a href="{% url 'products' %}" class="btn btn-grey mt-2">
                                <span class="icon">
                                    <i class="fas fa-chevron-left"></i>
                                </span>
                                <span class="text-uppercase">Keep Shopping</span>
                            </a>
                            <input type="submit" class="btn btn-red text-uppercase mt-2" value="Add to Bag">
                        </div>
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}